org: skillupdev
app: skillup
service: api-connector

frameworkVersion: '2'

useDotenv: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline

provider:
  name: aws
  runtime: nodejs14.x
  region: us-east-1
  lambdaHashingVersion: '20201221'
  iam:
    role:
      name: ${env:AWS_IAM_NAME}
      path: /
      statements:
        - Effect: "Allow"
          Action:
            - s3:PutObject
          Resource: "arn:aws:s3:::${env:AWS_BUCKET}/*"
        - Effect: "Deny"
          Action:
            - s3:DeleteObject
          Resource: "arn:aws:s3:::${env:AWS_BUCKET}/*"

functions:
  fortnite:
    handler: handler.fortnite
    events:
      - http:
          path: /fortnite
          method: get
      # Invoke Lambda function every 30 minute
      - schedule: cron(0/30 * * * ? *)
    environment:
      AWS_BUCKET: ${env:AWS_BUCKET}
      AWS_BUCKET_CDN_URL: ${env:AWS_BUCKET_CDN_URL}
      FORTNITE_API_KEY: ${env:FORTNITE_API_KEY}
      INTERNAL_API_KEY: ${env:INTERNAL_API_KEY}
      INTERNAL_API_URL: ${env:INTERNAL_API_URL}
    provisionedConcurrency: 1
